# https://docs.travis-ci.com/user/customizing-the-build/
language: java

script: mvn test

notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false

# https://docs.travis-ci.com/user/notifications/#IRC-notification
notifications:
  irc: "irc.freenode.org#softhaus"
